version: "2"
services:
  api:
    image: distribrewed/master:api-x64
    network_mode: host
    environment:
      AMQP_HOST: localhost
      AMQP_PORT: "5672"
      AMQP_USER: ${AMQP_USER}
      AMQP_PASS: ${AMQP_PASS}
      AMQP_VHOST: ${AMQP_VHOST}
      DB_HOST: localhost
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    restart: always
  queue:
    image: distribrewed/master:queue-x64
    network_mode: host
    environment:
      AMQP_HOST: localhost
      AMQP_PORT: "5672"
      AMQP_USER: ${AMQP_USER}
      AMQP_PASS: ${AMQP_PASS}
      AMQP_VHOST: ${AMQP_VHOST}
      DB_HOST: localhost
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    restart: always
  postgres:
    image: distribrewed/postgres:x64
    network_mode: host
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    network_mode: host
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASS}
      RABBITMQ_DEFAULT_VHOST: ${AMQP_VHOST}
    restart: always
  prometheus:
    image: distribrewed/prometheus:x64
    network_mode: host
    restart: always
    volumes:
      - "./data/prometheus:/prometheus/data"
  consul:
    image: consul
    network_mode: host
    environment:
      CONSUL_LOCAL_CONFIG: '{"datacenter": "distribrewed"}'
    restart: always
  grafana:
    image: grafana/grafana
    network_mode: host
    restart: always
    volumes:
      - "./data/grafana:/var/lib/grafana"
