version: "2"
services:
  telegram:
    image: distribrewed/workers:x64
    network_mode: host
    env_file:
      - ../.env
    environment:
      AMQP_HOST: localhost
      WORKER_NAME: telegram
      WORKER_PLUGIN_CLASS: TelegramWorker
      TELEGRAM_CHAT: ${TELEGRAM_CHAT}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    restart: always